// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iqckwjkndvbftbivyatt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlxY2t3amtuZHZiZnRiaXZ5YXR0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg1NTc0MjQsImV4cCI6MjA2NDEzMzQyNH0.VHTgPt6sU2ZgWkGlmp8_tqcO6u6EUy4m__RW5-sDYk0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);