
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { ScrollArea } from "@/components/ui/scroll-area";
import { Badge } from "@/components/ui/badge";
import { Sparkles } from "lucide-react";

interface TestRecord {
  [key: string]: any;
}

interface GeneratedDataTableProps {
  generatedData: TestRecord[];
}

const GeneratedDataTable = ({ generatedData }: GeneratedDataTableProps) => {
  return (
    <Card>
      <CardHeader>
        <CardTitle className="flex items-center gap-2">
          <Sparkles className="h-5 w-5 text-blue-500" />
          OpenAI Generated Test Scenarios
        </CardTitle>
        <p className="text-sm text-muted-foreground">
          Intelligent test data scenarios generated by OpenAI to validate your SQL query
        </p>
      </CardHeader>
      <CardContent>
        <div className="border rounded-lg">
          <ScrollArea className="h-[400px]">
            <Table>
              <TableHeader>
                <TableRow>
                  {generatedData.length > 0 && Object.keys(generatedData[0]).map(key => (
                    <TableHead key={key} className="min-w-[120px]">
                      {key.replace(/_/g, ' ').toUpperCase()}
                    </TableHead>
                  ))}
                </TableRow>
              </TableHeader>
              <TableBody>
                {generatedData.map((row, index) => (
                  <TableRow key={index}>
                    {Object.entries(row).map(([key, value], cellIndex) => (
                      <TableCell key={cellIndex} className="font-mono text-sm">
                        {key === 'test_scenario' ? (
                          <Badge variant="outline" className="text-xs">
                            {String(value)}
                          </Badge>
                        ) : value === null ? (
                          <span className="text-gray-400 italic">NULL</span>
                        ) : (
                          String(value)
                        )}
                      </TableCell>
                    ))}
                  </TableRow>
                ))}
              </TableBody>
            </Table>
          </ScrollArea>
        </div>
      </CardContent>
    </Card>
  );
};

export default GeneratedDataTable;
